
// Import your product images
import image0 from "../../assets/images/abc.png";
import image01 from "../../assets/images/i2.jpeg";
import image1 from "../../assets/images/Elegant white coat.jpg";
import image2 from "../../assets/images/digitalcandle.jpg";
import image3 from "../../assets/images/Giveaway.png";
import image4 from "../../assets/images/Sculptural Interior Accent.jpg";
import image5 from "../../assets/images/hat.jpg";
import image6 from "../../assets/images/Minimalist Bag Display.jpg";
import image7 from "../../assets/images/Minimalist Interior.jpg";
import image8 from "../../assets/images/Minimalist Wall Clock.jpg";
import image9 from "../../assets/images/old.jpg";
import image10 from "../../assets/images/Serene Plant Display.jpg";
const products = [
  {
    id: 1,
    name: "Elegant Wall Mirror",
    Email: "sham990807@gmail.com", image: image0,image01,
    category: "Wall Decor",
    description: "Beautifully crafted round mirror with golden frame, perfect for adding depth to any room.",
    rating: 4.6,
    owner: "Reflections Co.",
    vendor: "Reflections Co.",
    location: "New York, NY",
    phone: "555-1234",
    price: 89.99,
    discountedPrice: 79.99,
    label: "Bestseller",
    stock: 50,
    dimensions: "24 inch diameter",
    material: "Glass, Metal",
    color: "Gold",
    specifications: {
      frameType: "Round",
      frameMaterial: "Metal",
      glassMaterial: "Tempered Glass",
      backingMaterial: "MDF",
      hangingMethod: "Wall Mount"
    }
  },
  {
    id: 2,
    name: "Cozy Throw Blanket",
    Email: "sham990807@gmail.com", image: image2,image3,
    category: "Textiles",
    description: "Soft and warm throw blanket made from premium cotton, ideal for snuggling on the couch.",
    rating: 4.8,
    owner: "Comfort Haven",
    vendor: "Comfort Haven",
    location: "Los Angeles, CA",
    phone: "555-5678",
    price: 49.99,
    discountedPrice: 39.99,
    label: "Sale",
    stock: 100,
    dimensions: "50x60 inches",
    material: "100% Cotton",
    color: "Cream",
    specifications: {
      fabricType: "100% Cotton",
      fabricWeight: "300 GSM",
      edgeFinish: "Hemmed",
      washingInstructions: "Machine Wash Cold, Tumble Dry Low"
    }
  },
  {
    id: 3,
    name: "Minimalist Table Lamp",
    Email: "sham990807@gmail.com", image: image3,image4,
    category: "Lighting",
    description: "Sleek and modern table lamp with adjustable arm, perfect for reading or ambient lighting.",
    rating: 4.5,
    owner: "Illuminate Design",
    vendor: "Illuminate Design",
    location: "Chicago, IL",
    phone: "555-9012",
    price: 69.99,
    discountedPrice: 59.99,
    label: "New Arrival",
    stock: 75,
    dimensions: "15 inches tall",
    material: "Metal, Fabric",
    color: "Black",
    specifications: {
      lampType: "Table Lamp",
      lightSource: "LED Bulb (Included)",
      maxWattage: "60W",
      dimmable: "Yes",
      switchType: "Rotary"
    }
  },
  {
    id: 4,
    name: "Decorative Throw Pillows Set",
    Email: "sham990807@gmail.com", image: image4,image5,
    category: "Textiles",
    description: "Set of 4 stylish throw pillows with various patterns, adding a pop of color to any space.",
    rating: 4.7,
    owner: "Pillow Paradise",
    vendor: "Pillow Paradise",
    location: "Seattle, WA",
    phone: "555-3456",
    price: 59.99,
    discountedPrice: 49.99,
    label: "Limited Edition",
    stock: 30,
    dimensions: "18x18 inches each",
    material: "Cotton, Polyester",
    color: "Multi-color",
    specifications: {
      pillowCount: "4",
      fillMaterial: "Polyester Fiber",
      fabricType: "Cotton Blend",
      fabricPattern: "Assorted Patterns",
      zipperClosures: "Yes"
    }
  },
  {
    id: 5,
    name: "Rustic Wall Clock",
    Email: "sham990807@gmail.com", image: image5,image6,
    category: "Wall Decor",
    description: "Large rustic wall clock with wooden frame, bringing a touch of farmhouse charm to your home.",
    rating: 4.4,
    owner: "Timeless Treasures",
    vendor: "Timeless Treasures",
    location: "Austin, TX",
    phone: "555-7890",
    price: 79.99,
    discountedPrice: 69.99,
    label: "Handcrafted",
    stock: 40,
    dimensions: "30 inch diameter",
    material: "Wood, Metal",
    color: "Brown",
    specifications: {
      clockType: "Wall Clock",
      frameMaterial: "Solid Wood",
      clockFace: "Analog",
      movementType: "Quartz",
      batteriesRequired: "1 AA (Included)"
    }
  },
  {
    id: 6,
    name: "Geometric Bookends",
    Email: "sham990807@gmail.com", image: image6,image7,
    category: "Accessories",
    description: "Modern geometric bookends in rose gold, perfect for organizing your favorite reads in style.",
    rating: 4.3,
    owner: "Novel Nook",
    vendor: "Novel Nook",
    location: "Miami, FL",
    phone: "555-2345",
    price: 34.99,
    discountedPrice: 29.99,
    label: "Trendy",
    stock: 60,
    dimensions: "6x4x6 inches each",
    material: "Metal",
    color: "Rose Gold",
    specifications: {
      bookendCount: "2",
      bookendShape: "Geometric",
      bookendMaterial: "Metal Alloy",
      bookendFinish: "Rose Gold",
      bookendWeight: "2 lbs each"
    }
  },
  {
    id: 7,
    name: "Macrame Wall Hanging",
    Email: "sham990807@gmail.com", image: image7,image8,
    category: "Wall Decor",
    description: "Handmade macrame wall hanging, adding texture and boho charm to any wall.",
    rating: 4.6,
    owner: "Boho Bliss",
    vendor: "Boho Bliss",
    location: "Portland, OR",
    phone: "555-6789",
    price: 54.99,
    discountedPrice: 49.99,
    label: "Artisan",
    stock: 25,
    dimensions: "24x36 inches",
    material: "Cotton Rope",
    color: "Off-white",
    specifications: {
      hangingMethod: "Wall Mounted",
      ropeMaterial: "100% Cotton",
      ropeThickness: "5mm",
      patternDesign: "Macrame",
      handcrafted: "Yes"
    }
  },
  {
    id: 8,
    name: "Scented Soy Candle Set",
    Email: "sham990807@gmail.com", image: image8,
    category: "Furniture",
    description: "Set of 3 scented soy candles in glass jars, creating a cozy and aromatic atmosphere.",
    rating: 4.9,
    owner: "Serene Scents",
    vendor: "Serene Scents",
    location: "Denver, CO",
    phone: "555-0123",
    price: 39.99,
    discountedPrice: 34.99,
    label: "Eco-friendly",
    stock: 80,
    dimensions: "3x3 inches each",
    material: "Soy Wax, Glass",
    scents: "Lavender, Vanilla, Sandalwood",
    specifications: {
      candles: "3",
      candleType: "Soy Wax",
      candleJarMaterial: "Glass",
      candleWickType: "Cotton",
      burnTime: "Up to 40 hours per candle"
    }
  },
  {
    id: 9,
    name: "Abstract Canvas Wall Art",
    Email: "sham990807@gmail.com", image: image9,
    category: "Wall Decor",
    description: "Vibrant abstract canvas print, making a bold statement in any room.",
    rating: 4.7,
    owner: "Artistic Aura",
    vendor: "Artistic Aura",
    location: "San Francisco, CA",
    phone: "555-4567",
    price: 129.99,
    discountedPrice: 109.99,
    label: "Gallery Quality",
    stock: 20,
    dimensions: "36x48 inches",
    material: "Canvas, Wood Frame",
    style: "Contemporary",
    specifications: {
      artMedium: "Acrylic Paint",
      canvasType: "Stretched Canvas",
      frameMaterial: "Solid Wood",
      frameFinish: "Matte Black",
      hangingMethod: "Wall Mount"
    }
  },
  {
    id: 10,
    name: "Ceramic Vase Set",
    Email: "sham990807@gmail.com", image: image10,
    category: "Accessories",
    description: "Set of 3 modern ceramic vases in varying sizes, perfect for displaying fresh or dried flowers.",
    rating: 4.5,
    owner: "Pottery Plus",
    vendor: "Pottery Plus",
    location: "Atlanta, GA",
    phone: "555-8901",
    price: 64.99,
    discountedPrice: 54.99,
    label: "Versatile",
    stock: 35,
    dimensions: "4, 6, and 8 inches tall",
    material: "Ceramic",
    color: "White, Gray, Black",
    specifications: {
      vaseCount: "3",
      vaseSizes: "4 inch, 6 inch, 8 inch",
      vaseMaterial: "Ceramic",
      vaseFinish: "Matte",
      vaseShape: "Cylindrical"
    }
  },
  {
    id: 11,
    name: "Floating Wall Shelves",
    Email: "sham990807@gmail.com", image: image1,
    category: "Accessories",
    description: "Set of 3 wooden floating shelves, ideal for displaying decor or organizing small items.",
    rating: 4.4,
    owner: "Shelf Solutions",
    vendor: "Shelf Solutions",
    location: "Seattle, WA",
    phone: "555-2345",
    price: 49.99,
    discountedPrice: 44.99,
    label: "Space-saving",
    stock: 55,
    dimensions: "16, 20, 24 inches wide",
    material: "Wood",
    color: "Walnut",
    specifications: {
      shelfCount: "3",
      shelfSizes: "16 inch, 20 inch, 24 inch",
      shelfMaterial: "Solid Wood",
      shelfFinish: "Walnut Stain",
      mountingHardware: "Included"
    }
  },
  {
    id: 12,
    name: "Decorative Table Runner",
    Email: "sham990807@gmail.com", image: image2,
    category: "Textiles",
    description: "Elegant table runner with intricate embroidery, perfect for dressing up your dining table.",
    rating: 4.6,
    owner: "Table Charm",
    vendor: "Table Charm",
    location: "Chicago, IL",
    phone: "555-6789",
    price: 29.99,
    discountedPrice: 24.99,
    label: "Festive",
    stock: 70,
    dimensions: "14x72 inches",
    material: "Polyester",
    color: "Sage Green",
    specifications: {
      fabricType: "Polyester",
      embroideryDesign: "Floral",
      edgeFinish: "Hemmed",
      washingInstructions: "Machine Wash Cold, Tumble Dry Low"
    }
  },
  {
    id: 13,
    name: "Moroccan Pouf Ottoman",
    Email: "sham990807@gmail.com", image: image3,
    category: "Furniture",
    description: "Handcrafted leather pouf ottoman, adding exotic flair and extra seating to any room.",
    rating: 4.8,
    owner: "Global Goods",
    vendor: "Global Goods",
    location: "New York, NY",
    phone: "555-0123",
    price: 89.99,
    discountedPrice: 79.99,
    label: "Authentic",
    stock: 15,
    dimensions: "20x20x14 inches",
    material: "Leather",
    color: "Tan",
    specifications: {
      poufeType: "Ottoman",
      fabricMaterial: "100% Genuine Leather",
      fillMaterial: "Polystyrene Beads",
      handcrafted: "Yes",
      origin: "Morocco"
    }
  },
  {
    id: 14,
    name: "Succulent Planter Set",
    Email: "sham990807@gmail.com", image: image4,
    category: "Wall Decor",
    description: "Set of 5 small ceramic planters with bamboo tray, perfect for displaying mini succulents.",
    rating: 4.7,
    owner: "Green Thumb",
    vendor: "Green Thumb",
    location: "Los Angeles, CA",
    phone: "555-4567",
    price: 39.99,
    discountedPrice: 34.99,
    label: "Gardener's Choice",
    stock: 40,
    dimensions: "2.5 inch diameter each",
    material: "Ceramic, Bamboo",
    color: "White, Tray: Natural",
    specifications: {
      planterCount: "5",
      planterMaterial: "Ceramic",
      planterSize: "2.5 inch diameter",
      trayMaterial: "Bamboo",
      trayDimensions: "12x6 inches"
    }
  },
  {
    id: 15,
    name: "Decorative Wind Chimes",
    Email: "sham990807@gmail.com", image: image5,
    category: "Outdoor",
    description: "Melodic wind chimes with brushed aluminum tubes and wooden accents, creating soothing sounds.",
    rating: 4.5,
    owner: "Harmony Home",
    vendor: "Harmony Home",
    location: "Austin, TX",
    phone: "555-8901",
    price: 44.99,
    discountedPrice: 39.99,
    label: "Relaxing",
    stock: 30,
    dimensions: "28 inches long",
    material: "Aluminum, Wood",
    color: "Silver, Brown",
    specifications: {
      tubeMaterial: "Brushed Aluminum",
      accentMaterial: "Solid Wood",
      totalTubes: "6",
      hangingMethod: "Hanging Chain",
      soundType: "Melodic Chimes"
    }
  },
  {
    id: 16,
    name: "Vintage-inspired Wall Clock",
    Email: "sham990807@gmail.com", image: image6,
    category: "Wall Decor",
    description: "Charming wall clock with a distressed finish, bringing a touch of nostalgia to your decor.",
    rating: 4.3,
    owner: "Retro Relics",
    vendor: "Retro Relics",
    location: "Miami, FL",
    phone: "555-2345",
    price: 59.99,
    discountedPrice: 49.99,
    label: "Vintage Look",
    stock: 25,
    dimensions: "18 inch diameter",
    material: "Metal",
    color: "Antique White",
    specifications: {
      clockType: "Wall Clock",
      clockFace: "Analog",
      movementType: "Quartz",
      batteriesRequired: "1 AA (Included)",
      finishType: "Distressed"
    }
  },
  {
    id: 17,
    name: "Velvet Accent Pillow",
    Email: "sham990807@gmail.com", image: image7,
    category: "Textiles",
    description: "Luxurious velvet accent pillow with tassels, adding a touch of elegance to any sofa or bed.",
    rating: 4.6,
    owner: "Plush Paradise",
    vendor: "Plush Paradise",
    location: "Denver, CO",
    phone: "555-6789",
    price: 29.99,
    discountedPrice: 24.99,
    label: "Luxe",
    stock: 60,
    dimensions: "18x18 inches",
    material: "Velvet",
    color: "Emerald Green",
    specifications: {
      pillowType: "Accent Pillow",
      fabricMaterial: "100% Velvet",
      fillMaterial: "Polyester Fiber",
      accentDetails: "Tassels",
      zipperClosures: "Yes"
    }
  },
  {
    id: 18,
    name: "Hanging Terrarium",
    Email: "sham990807@gmail.com", image: image8,
    category: "Wall Decor",
    description: "Glass hanging terrarium with metal frame, perfect for displaying air plants or small succulents.",
    rating: 4.4,
    owner: "Botanical Bliss",
    vendor: "Botanical Bliss",
    location: "Portland, OR",
    phone: "555-0123",
    price: 34.99,
    discountedPrice: 29.99,
    label: "Modern Garden",
    stock: 40,
    dimensions: "6 inch diameter",
    material: "Glass, Metal",
    color: "Black frame",
    specifications: {
      terrariumType: "Hanging",
      terrariumMaterial: "Glass, Metal",
      terrariumSize: "6 inch diameter",
      plantCompatibility: "Air Plants, Succulents",
      hangingMethod: "Chain"
    }
  },
  {
    id: 19,
    name: "Decorative Wall Hooks",
    Email: "sham990807@gmail.com", image: image9,
    category: "Accessories",
    description: "Set of 5 decorative wall hooks in various designs, perfect for hanging coats, bags, or keys.",
    rating: 4.7,
    owner: "Organized Spaces",
    vendor: "Organized Spaces",
    location: "Atlanta, GA",
    phone: "555-4567",
    price: 24.99,
    discountedPrice: 19.99,
    label: "Functional Decor",
    stock: 75,
    dimensions: "3-5 inches each",
    material: "Metal",
    color: "Brass",
    specifications: {
      hookCount: "5",
      hookMaterial: "Metal",
      hookFinish: "Brass",
      hookDesigns: "Assorted",
      hookSize: "3-5 inches"
    }
  },
  {
    id: 20,
    name: "Faux Fur Rug",
    Email: "sham990807@gmail.com", image: image10,
    category: "Textiles",
    description: "Soft and plush faux fur rug, adding warmth and texture to any room.",
    rating: 4.8,
    owner: "Cozy Comforts",
    vendor: "Cozy Comforts",
    location: "Chicago, IL",
    phone: "555-8901",
    price: 79.99,
    discountedPrice: 69.99,
    label: "Luxurious",
    stock: 30,
    dimensions: "3x5 feet",
    material: "Faux Fur",
    color: "Arctic White",
    specifications: {
      rugType: "Area Rug",
      rugSize: "3x5 feet",
      rugMaterial: "100% Polyester Faux Fur",
      rugPile: "Long, Plush",
      rugBackingMaterial: "Non-Slip Rubber"
    }
  },
  {
    id: 21,
    name: "Copper String Lights",
    Email: "sham990807@gmail.com", image: image1,
    category: "Lighting",
    description: "Warm LED string lights with copper wire, creating a magical ambiance in any space.",
    rating: 4.5,
    owner: "Twinkle Town",
    vendor: "Twinkle Town",
    location: "San Francisco, CA",
    phone: "555-2345",
    price: 19.99,
    discountedPrice: 17.99,
    label: "Mood Lighting",
    stock: 100,
    dimensions: "33 feet long",
    material: "Copper Wire, LED",
    color: "Warm White",
    specifications: {
      lightType: "String Lights",
      lightSource: "LED",
      wireMaterial: "Copper",
      lightLength: "33 feet",
      lightColor: "Warm White"
    }
  },
  {
    id: 22,
    name: "Minimalist Wall Shelf",
    Email: "sham990807@gmail.com", image: image2,
    category: "Accessories",
    description: "Sleek metal wall shelf with wooden accents, perfect for displaying small decor items.",
    rating: 4.6,
    owner: "Modern Mounts",
    vendor: "Modern Mounts",
    location: "New York, NY",
    phone: "555-6789",
    price: 44.99,
    discountedPrice: 39.99,
    label: "Scandinavian Style",
    stock: 50,
    dimensions: "24x6x6 inches",
    material: "Metal, Wood",
    color: "Black, Natural Wood",
    specifications: {
      shelfCount: "1",
      shelfSize: "24x6x6 inches",
      shelfMaterial: "Metal, Wood",
      shelfFinish: "Matte Black, Natural Wood",
      mountingHardware: "Included"
    }
  },
  {
    id: 23,
    name: "Decorative Glass Vase",
    Email: "sham990807@gmail.com", image: image3,
    category: "Accessories",
    description: "Elegant hand-blown glass vase with unique swirl pattern, perfect for fresh or dried flowers.",
    rating: 4.7,
    owner: "Artisan Accents",
    vendor: "Artisan Accents",
    location: "Los Angeles, CA",
    phone: "555-0123",
    price: 54.99,
    discountedPrice: 49.99,
    label: "Handcrafted",
    stock: 20,
    dimensions: "10 inches tall",
    material: "Glass",
    color: "Blue Ombre",
    specifications: {
      vaseType: "Decorative",
      vaseMaterial: "Hand-Blown Glass",
      vaseHeight: "10 inches",
      vaseFinish: "Blue Ombre",
      vaseDesign: "Swirl Pattern"
    }
  },
  {
    id: 24,
    name: "Woven Wall Basket",
    Email: "sham990807@gmail.com", image: image4,
    category: "Wall Decor",
    description: "Handwoven seagrass wall basket, adding texture and boho charm to any wall.",
    rating: 4.4,
    owner: "Natural Nook",
    vendor: "Natural Nook",
    location: "Miami, FL",
    phone: "555-4567",
    price: 39.99,
    discountedPrice: 34.99,
    label: "Eco-friendly",
    stock: 35,
    dimensions: "16 inch diameter",
    material: "Seagrass",
    color: "Natural",
    specifications: {
      basketType: "Wall Basket",
      basketMaterial: "Handwoven Seagrass",
      basketSize: "16 inch diameter",
      basketFinish: "Natural",
      hangingMethod: "Wall Mount"
    }
  },
  {
    id: 25,
    name: "Marble Serving Tray",
    Email: "sham990807@gmail.com", image: image5,
    category: "Accessories",
    description: "Elegant white marble serving tray with gold handles, perfect for entertaining or display.",
    rating: 4.9,
    owner: "Luxe Living",
    vendor: "Luxe Living",
    location: "Denver, CO",
    phone: "555-8901",
    price: 69.99,
    discountedPrice: 59.99,
    label: "Elegant",
    stock: 25,
    dimensions: "16x10 inches",
    material: "Marble, Metal",
    color: "White, Gold",
    specifications: {
      trayType: "Serving Tray",
      trayMaterial: "Marble, Metal",
      traySize: "16x10 inches",
      trayFinish: "White Marble, Gold Handles",
      trayDesign: "Rectangular"
    }
  }
];
export default products;